#ifndef DAC_RATE_TEST_FML_H
#define DAC_RATE_TEST_FML_H

#include "main.h"

#define DAC_RATE_TEST_SAMPLE_RATE_HZ 1000000U
#define DAC_RATE_TEST_BUFFER_SAMPLES 1024U
#define DAC_RATE_TEST_SINE_FREQUENCY_HZ \
    ((float32_t)DAC_RATE_TEST_SAMPLE_RATE_HZ / (float32_t)DAC_RATE_TEST_BUFFER_SAMPLES)
#define DAC_RATE_TEST_SINE_VPP_V 2.0f
#define DAC_RATE_TEST_SINE_OFFSET_V 1.65f

HAL_StatusTypeDef DAC_RateTest_FML_Start(void);

#endif /* DAC_RATE_TEST_FML_H */
