#ifndef __IIR_FML_H__
#define __IIR_FML_H__

#include "arm_math.h"
#include <stdbool.h>
#include <stdint.h>

/*
 * Continuous-time target transfer function (unity DC gain):
 *
 *                  1
 * H(s) = --------------------------
 *        1e-8 s^2 + 3e-4 s + 1
 *
 * Coefficients are generated by a bilinear transform for the specified
 * sampling rate.  The reference AD-to-DA project uses 2 MS/s.
 */
#define IIR_LOWPASS_REFERENCE_SAMPLE_RATE_HZ 2000000.0f

typedef struct
{
    arm_biquad_casd_df1_inst_f32 instance;
    float32_t coefficients[5]; /* CMSIS order: b0, b1, b2, a1, a2. */
    float32_t state[4];
    float32_t sample_rate_hz;
    uint32_t signature;
} iir_lowpass_filter_t;

bool IIR_Lowpass_Init(iir_lowpass_filter_t *filter, float32_t sample_rate_hz);
void IIR_Lowpass_Reset(iir_lowpass_filter_t *filter);

/* Input and output may refer to the same float buffer. */
bool IIR_Lowpass_Process(iir_lowpass_filter_t *filter,
                         const float32_t *input,
                         float32_t *output,
                         uint32_t sample_count);

/*
 * Helper for the ADC-to-DAC path used by the reference project. ADC data is
 * represented as Q15 around adc_midpoint_code, converted to float for the
 * CMSIS DF1 biquad, quantized back to Q15, shifted to dac_midpoint_code, and
 * saturated to the 12-bit DAC range. Each scratch buffer must contain at
 * least sample_count elements.
 */
bool IIR_Lowpass_ProcessAdc12ToDac12(iir_lowpass_filter_t *filter,
                                     const uint16_t *adc_codes,
                                     uint16_t *dac_codes,
                                     q15_t *q15_scratch,
                                     float32_t *scratch,
                                     uint32_t sample_count,
                                     uint16_t adc_midpoint_code,
                                     uint16_t dac_midpoint_code);

const float32_t *IIR_Lowpass_GetCoefficients(const iir_lowpass_filter_t *filter);
float32_t IIR_Lowpass_GetSampleRate(const iir_lowpass_filter_t *filter);

#endif
